site_name: AI Planning Research Project

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: false
          docstring_section_style: list
          docstring_style: google
          heading_level: 5
          members_order: source
          merge_init_into_class: true
          separate_signature: true
          show_category_heading: false
          show_if_no_docstring: false
          show_signature_annotations: true
          show_source: false
          show_root_toc_entry: false

nav:
  - Home: index.md
  - Overview: overview.md
  - Example CDCL search: cdcl_example.md
  - Reference:
    - Fundamentals: fundamentals.md
    - Constraint Expressions: constraint_expressions.md
    - Solver:
      - Common: common.md
      - Solver State: solver_state.md
      - Solver Main Class: solver.md
      - Reasoners:
        - Reasoner: reasoner.md 
        - SAT Reasoner: sat_reasoner.md 
        - Difference Logic Reasoner: diff_reasoner.md 
      - Branchers:
        - Brancher: brancher.md
  
extra_css:
 - stylesheets/extra_style.css